apiVersion: app/v1
kind: Deployment
metadata: 
  name: second-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpresssions:
    #   - {key: app, operator: In, values: [first-app, second-app]}
  template: 
    metadata:
      labels:
        app: second-app
        tier: backend
    spec: 
      containers:
        - name: second-node
          image: zkrakus/kub-first-app:2
          imagePullPolciy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              periodSeconds: 10
              initialDelaySeconds: 5